name = "physics-site"
compatibility_date = "2024-04-03"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "physics-blog-db"
database_id = "d11dbfad-e50b-451d-8ba0-724246cfc858"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "physics-blog-assets"
