name = "physicsfundamentals"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

assets = { directory = ".open-next/assets" }

[[d1_databases]]
binding = "DB"
database_name = "physics-blog-db"
database_id = "d11dbfad-e50b-451d-8ba0-724246cfc858"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "physics-blog-assets"
